import { 
  Startup, 
  Investor, 
  Interest, 
  Meeting, 
  Document, 
  DocumentView, 
  StartupUpdate, 
  AnalyticsEvent, 
  MomentumScore,
  InterestLevel,
  MeetingStatus
} from './types';

// Helper function to generate random ID
const generateId = () => Math.random().toString(36).substring(2, 15);

// Helper function to get random date within last N days
const getRandomDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - Math.floor(Math.random() * daysAgo));
  return date;
};

// Mock Startups Data
export const mockStartups: Startup[] = [
  {
    id: 'startup-1',
    userId: 'user-founder-1',
    name: 'NeuralFlow AI',
    tagline: 'Autonomous AI agents for enterprise data pipelines',
    description: 'NeuralFlow transforms how enterprises handle data by deploying autonomous AI agents that monitor, optimize, and heal data pipelines in real-time. Built on cutting-edge LLM technology with custom fine-tuning for data engineering tasks.',
    industry: 'AI/ML',
    stage: 'Seed',
    fundingGoal: 2000000,
    website: 'https://neuralflow.ai',
    logoUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=neuralflow',
    pitchDeckUrl: '/decks/neuralflow-deck.pdf',
    demoDayBatch: 'Spring 2026',
    pitchDate: new Date('2026-05-19'),
    qrCode: 'QR-NEURAL-001',
    founderName: 'Sarah Chen',
    founderEmail: 'sarah@neuralflow.ai',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'startup-2',
    userId: 'user-founder-2',
    name: 'QuantumHealth',
    tagline: 'AI-powered early cancer detection from routine blood work',
    description: 'QuantumHealth uses proprietary machine learning models to detect cancer biomarkers 18-24 months earlier than traditional methods, using only standard blood tests. Clinical trials show 94% accuracy across 12 cancer types.',
    industry: 'Healthcare',
    stage: 'Series A',
    fundingGoal: 8000000,
    website: 'https://quantumhealth.io',
    logoUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=quantum',
    pitchDeckUrl: '/decks/quantum-deck.pdf',
    demoDayBatch: 'Spring 2026',
    pitchDate: new Date('2026-05-19'),
    qrCode: 'QR-QUANTUM-002',
    founderName: 'Dr. James Wu',
    founderEmail: 'james@quantumhealth.io',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    createdAt: new Date('2025-11-20'),
  },
  {
    id: 'startup-3',
    userId: 'user-founder-3',
    name: 'GreenVolt Energy',
    tagline: 'Next-gen solid-state batteries for EVs',
    description: 'GreenVolt has developed solid-state battery technology that delivers 3x the energy density of lithium-ion at 40% lower cost. Already in partnership discussions with two major EV manufacturers.',
    industry: 'Clean Tech',
    stage: 'Seed',
    fundingGoal: 5000000,
    website: 'https://greenvolt.energy',
    logoUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=greenvolt',
    pitchDeckUrl: '/decks/greenvolt-deck.pdf',
    demoDayBatch: 'Spring 2026',
    pitchDate: new Date('2026-05-19'),
    qrCode: 'QR-GREEN-003',
    founderName: 'Maya Patel',
    founderEmail: 'maya@greenvolt.energy',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maya',
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 'startup-4',
    userId: 'user-founder-4',
    name: 'RoboChef',
    tagline: 'Autonomous robotic kitchen for restaurants',
    description: 'RoboChef automates commercial kitchens with AI-powered robots that can prep, cook, and plate 200+ dishes. Reduces labor costs by 60% while maintaining Michelin-quality consistency.',
    industry: 'Robotics',
    stage: 'Pre-Seed',
    fundingGoal: 1500000,
    website: 'https://robochef.io',
    logoUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=robochef',
    pitchDeckUrl: '/decks/robochef-deck.pdf',
    demoDayBatch: 'Spring 2026',
    pitchDate: new Date('2026-05-19'),
    qrCode: 'QR-ROBO-004',
    founderName: 'Alex Rivera',
    founderEmail: 'alex@robochef.io',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'startup-5',
    userId: 'user-founder-5',
    name: 'TalentAI',
    tagline: 'AI recruiting that eliminates bias and finds hidden gems',
    description: 'TalentAI uses behavioral science and machine learning to assess candidates purely on potential and culture fit, removing demographic bias. Companies using our platform have seen 40% improvement in retention and 3x more diverse hires.',
    industry: 'HR Tech',
    stage: 'Seed',
    fundingGoal: 3000000,
    website: 'https://talent-ai.com',
    logoUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=talentai',
    pitchDeckUrl: '/decks/talentai-deck.pdf',
    demoDayBatch: 'Spring 2026',
    pitchDate: new Date('2026-05-19'),
    qrCode: 'QR-TALENT-005',
    founderName: 'Jordan Lee',
    founderEmail: 'jordan@talent-ai.com',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    createdAt: new Date('2025-12-05'),
  },
];

// Mock Investors Data
export const mockInvestors: Investor[] = [
  {
    id: 'investor-1',
    userId: 'user-investor-1',
    name: 'Michael Chen',
    email: 'mchen@sequoia.com',
    firm: 'Sequoia Capital',
    title: 'Partner',
    investmentThesis: 'Focus on AI infrastructure and developer tools. Looking for technical founders solving hard problems in data, ML ops, and enterprise AI adoption.',
    sectors: ['AI/ML', 'Developer Tools', 'Enterprise SaaS'],
    stages: ['Seed', 'Series A'],
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    portfolioCompanies: ['OpenAI', 'Databricks', 'Snowflake', 'Stripe'],
    linkedinUrl: 'https://linkedin.com/in/michaelchen',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'investor-2',
    userId: 'user-investor-2',
    name: 'Emily Rodriguez',
    email: 'erodriguez@a16z.com',
    firm: 'Andreessen Horowitz',
    title: 'General Partner',
    investmentThesis: 'Investing in healthcare innovation, particularly AI-driven diagnostics and precision medicine. Passionate about democratizing access to quality healthcare.',
    sectors: ['Healthcare', 'Biotech', 'AI/ML'],
    stages: ['Seed', 'Series A', 'Series B'],
    checkSizeMin: 1000000,
    checkSizeMax: 15000000,
    portfolioCompanies: ['23andMe', 'Hims & Hers', 'Devoted Health'],
    linkedinUrl: 'https://linkedin.com/in/emilyrodriguez',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    createdAt: new Date('2024-06-15'),
  },
  {
    id: 'investor-3',
    userId: 'user-investor-3',
    name: 'David Park',
    email: 'dpark@lightspeed.com',
    firm: 'Lightspeed Venture Partners',
    title: 'Principal',
    investmentThesis: 'Climate tech and sustainable innovation. Investing in founders building solutions for decarbonization, circular economy, and energy transition.',
    sectors: ['Clean Tech', 'Climate', 'Energy'],
    stages: ['Pre-Seed', 'Seed'],
    checkSizeMin: 250000,
    checkSizeMax: 3000000,
    portfolioCompanies: ['Impossible Foods', 'Rubicon', 'Bright Machines'],
    linkedinUrl: 'https://linkedin.com/in/davidpark',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    createdAt: new Date('2025-03-20'),
  },
  {
    id: 'investor-4',
    userId: 'user-investor-4',
    name: 'Priya Sharma',
    email: 'psharma@nea.com',
    firm: 'NEA (New Enterprise Associates)',
    title: 'Venture Partner',
    investmentThesis: 'Consumer tech and future of work. Interested in products that change how people live, work, and interact. Strong focus on Gen Z platforms.',
    sectors: ['Consumer', 'Social', 'Future of Work', 'HR Tech'],
    stages: ['Seed', 'Series A'],
    checkSizeMin: 500000,
    checkSizeMax: 8000000,
    portfolioCompanies: ['Robinhood', 'Affirm', 'Discord', 'Plaid'],
    linkedinUrl: 'https://linkedin.com/in/priyasharma',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    createdAt: new Date('2024-09-10'),
  },
  {
    id: 'investor-5',
    userId: 'user-investor-5',
    name: 'Tom Anderson',
    email: 'tanderson@founder-collective.com',
    firm: 'Founder Collective',
    title: 'Managing Partner',
    investmentThesis: 'Backing outlier founders with unique insights. Sector agnostic but love robotics, automation, and hard tech. Former founder myself.',
    sectors: ['Robotics', 'Automation', 'Hard Tech', 'AI/ML'],
    stages: ['Pre-Seed', 'Seed'],
    checkSizeMin: 100000,
    checkSizeMax: 2000000,
    portfolioCompanies: ['Uber', 'PillPack', 'The Trade Desk', 'Coupang'],
    linkedinUrl: 'https://linkedin.com/in/tomanderson',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tom',
    createdAt: new Date('2025-02-14'),
  },
];

// Mock Interests Data
export const mockInterests: Interest[] = [
  {
    id: 'interest-1',
    startupId: 'startup-1',
    investorId: 'investor-1',
    investorName: 'Michael Chen',
    investorFirm: 'Sequoia Capital',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael',
    level: 'STRONGLY_INTERESTED',
    notes: 'Love the technical depth. Would like to discuss GTM strategy and competitive moat.',
    isAnonymous: false,
    scannedViaQR: true,
    scanTimestamp: new Date('2026-05-19T14:30:00'),
    createdAt: new Date('2026-05-19T14:30:00'),
  },
  {
    id: 'interest-2',
    startupId: 'startup-1',
    investorId: 'investor-4',
    investorName: 'Priya Sharma',
    investorFirm: 'NEA',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    level: 'WANT_TO_LEARN_MORE',
    isAnonymous: false,
    scannedViaQR: true,
    scanTimestamp: new Date('2026-05-19T15:00:00'),
    createdAt: new Date('2026-05-19T15:00:00'),
  },
  {
    id: 'interest-3',
    startupId: 'startup-2',
    investorId: 'investor-2',
    investorName: 'Emily Rodriguez',
    investorFirm: 'Andreessen Horowitz',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    level: 'STRONGLY_INTERESTED',
    notes: 'This is exactly what we are looking for in healthcare AI. Clinical validation is impressive. Let\'s schedule a deep dive on regulatory pathway.',
    isAnonymous: false,
    scannedViaQR: true,
    scanTimestamp: new Date('2026-05-19T14:45:00'),
    createdAt: new Date('2026-05-19T14:45:00'),
  },
  {
    id: 'interest-4',
    startupId: 'startup-3',
    investorId: 'investor-3',
    investorName: 'David Park',
    investorFirm: 'Lightspeed Venture Partners',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    level: 'STRONGLY_INTERESTED',
    notes: 'Battery tech breakthrough could be massive. Need to understand IP protection and manufacturing scalability.',
    isAnonymous: false,
    scannedViaQR: true,
    scanTimestamp: new Date('2026-05-19T15:15:00'),
    createdAt: new Date('2026-05-19T15:15:00'),
  },
  {
    id: 'interest-5',
    startupId: 'startup-4',
    investorId: 'investor-5',
    investorName: 'Tom Anderson',
    investorFirm: 'Founder Collective',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tom',
    level: 'STRONGLY_INTERESTED',
    notes: 'Robotics + food service is a huge market. Team has the right background. Want to see unit economics.',
    isAnonymous: false,
    scannedViaQR: true,
    scanTimestamp: new Date('2026-05-19T16:00:00'),
    createdAt: new Date('2026-05-19T16:00:00'),
  },
  {
    id: 'interest-6',
    startupId: 'startup-5',
    investorId: 'investor-4',
    investorName: 'Priya Sharma',
    investorFirm: 'NEA',
    investorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    level: 'WANT_TO_LEARN_MORE',
    notes: 'HR tech is hot. Curious about customer acquisition strategy and pricing model.',
    isAnonymous: false,
    scannedViaQR: false,
    createdAt: new Date('2026-05-20T10:00:00'),
  },
];

// Mock Meetings Data
export const mockMeetings: Meeting[] = [
  {
    id: 'meeting-1',
    startupId: 'startup-1',
    startupName: 'NeuralFlow AI',
    investorId: 'investor-1',
    investorName: 'Michael Chen',
    investorFirm: 'Sequoia Capital',
    title: 'Deep Dive on Technical Architecture',
    scheduledAt: new Date('2026-05-22T14:00:00'),
    duration: 60,
    status: 'CONFIRMED',
    meetingLink: 'https://zoom.us/j/123456789',
    createdAt: new Date('2026-05-19T16:00:00'),
  },
  {
    id: 'meeting-2',
    startupId: 'startup-2',
    startupName: 'QuantumHealth',
    investorId: 'investor-2',
    investorName: 'Emily Rodriguez',
    investorFirm: 'Andreessen Horowitz',
    title: 'Clinical Data Review & Regulatory Discussion',
    scheduledAt: new Date('2026-05-23T10:00:00'),
    duration: 90,
    status: 'CONFIRMED',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    notes: 'Please bring latest clinical trial results and FDA timeline',
    createdAt: new Date('2026-05-19T17:00:00'),
  },
  {
    id: 'meeting-3',
    startupId: 'startup-3',
    startupName: 'GreenVolt Energy',
    investorId: 'investor-3',
    investorName: 'David Park',
    investorFirm: 'Lightspeed Venture Partners',
    title: 'Battery Tech Deep Dive',
    scheduledAt: new Date('2026-05-24T15:00:00'),
    duration: 60,
    status: 'PENDING',
    createdAt: new Date('2026-05-20T09:00:00'),
  },
  {
    id: 'meeting-4',
    startupId: 'startup-4',
    startupName: 'RoboChef',
    investorId: 'investor-5',
    investorName: 'Tom Anderson',
    investorFirm: 'Founder Collective',
    title: 'Unit Economics & Scaling Strategy',
    scheduledAt: new Date('2026-05-21T11:00:00'),
    duration: 45,
    status: 'CONFIRMED',
    meetingLink: 'https://zoom.us/j/987654321',
    createdAt: new Date('2026-05-19T18:00:00'),
  },
];

// Mock Documents Data
export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    startupId: 'startup-1',
    title: 'NeuralFlow AI - Pitch Deck',
    type: 'pitch_deck',
    fileUrl: '/documents/neuralflow-deck.pdf',
    fileSize: 2500000,
    mimeType: 'application/pdf',
    createdAt: new Date('2026-05-15'),
  },
  {
    id: 'doc-2',
    startupId: 'startup-1',
    title: 'Financial Projections 2026-2028',
    type: 'financials',
    fileUrl: '/documents/neuralflow-financials.pdf',
    fileSize: 850000,
    mimeType: 'application/pdf',
    createdAt: new Date('2026-05-16'),
  },
  {
    id: 'doc-3',
    startupId: 'startup-2',
    title: 'QuantumHealth - Pitch Deck',
    type: 'pitch_deck',
    fileUrl: '/documents/quantum-deck.pdf',
    fileSize: 3200000,
    mimeType: 'application/pdf',
    createdAt: new Date('2026-05-10'),
  },
  {
    id: 'doc-4',
    startupId: 'startup-2',
    title: 'Clinical Trial Results',
    type: 'product_roadmap',
    fileUrl: '/documents/quantum-clinical.pdf',
    fileSize: 4500000,
    mimeType: 'application/pdf',
    createdAt: new Date('2026-05-12'),
  },
];

// Mock Document Views Data
export const mockDocumentViews: DocumentView[] = [
  {
    id: 'view-1',
    documentId: 'doc-1',
    viewerId: 'investor-1',
    viewerEmail: 'mchen@sequoia.com',
    viewerName: 'Michael Chen',
    viewerFirm: 'Sequoia Capital',
    duration: 420, // 7 minutes
    pagesViewed: 18,
    completionRate: 95,
    viewedAt: new Date('2026-05-19T15:30:00'),
  },
  {
    id: 'view-2',
    documentId: 'doc-1',
    viewerId: 'investor-4',
    viewerEmail: 'psharma@nea.com',
    viewerName: 'Priya Sharma',
    viewerFirm: 'NEA',
    duration: 180, // 3 minutes
    pagesViewed: 8,
    completionRate: 42,
    viewedAt: new Date('2026-05-20T09:15:00'),
  },
  {
    id: 'view-3',
    documentId: 'doc-2',
    viewerId: 'investor-1',
    viewerEmail: 'mchen@sequoia.com',
    viewerName: 'Michael Chen',
    viewerFirm: 'Sequoia Capital',
    duration: 600, // 10 minutes
    pagesViewed: 12,
    completionRate: 100,
    viewedAt: new Date('2026-05-19T16:00:00'),
  },
  {
    id: 'view-4',
    documentId: 'doc-3',
    viewerId: 'investor-2',
    viewerEmail: 'erodriguez@a16z.com',
    viewerName: 'Emily Rodriguez',
    viewerFirm: 'Andreessen Horowitz',
    duration: 540, // 9 minutes
    pagesViewed: 22,
    completionRate: 100,
    viewedAt: new Date('2026-05-19T17:00:00'),
  },
];

// Mock Analytics Data
export const mockAnalytics: AnalyticsEvent[] = [
  {
    id: 'analytics-1',
    startupId: 'startup-1',
    investorId: 'investor-1',
    investorName: 'Michael Chen',
    eventType: 'profile_view',
    eventData: { source: 'demo_day_qr' },
    timestamp: new Date('2026-05-19T14:30:00'),
  },
  {
    id: 'analytics-2',
    startupId: 'startup-1',
    investorId: 'investor-1',
    investorName: 'Michael Chen',
    eventType: 'document_view',
    eventData: { documentId: 'doc-1', duration: 420 },
    timestamp: new Date('2026-05-19T15:30:00'),
  },
  {
    id: 'analytics-3',
    startupId: 'startup-1',
    investorId: 'investor-1',
    investorName: 'Michael Chen',
    eventType: 'interest_expressed',
    eventData: { level: 'STRONGLY_INTERESTED' },
    timestamp: new Date('2026-05-19T14:30:00'),
  },
  {
    id: 'analytics-4',
    startupId: 'startup-2',
    investorId: 'investor-2',
    investorName: 'Emily Rodriguez',
    eventType: 'qr_scan',
    eventData: { qrCode: 'QR-QUANTUM-002' },
    timestamp: new Date('2026-05-19T14:45:00'),
  },
];

// Mock Momentum Scores Data
export const mockMomentumScores: MomentumScore[] = [
  {
    id: 'momentum-1',
    startupId: 'startup-1',
    score: 92,
    rank: 1,
    profileViews: 45,
    documentViews: 23,
    interestsCount: 2,
    meetingsCount: 1,
    lastCalculated: new Date(),
    trend: 'up',
    change: 15,
  },
  {
    id: 'momentum-2',
    startupId: 'startup-2',
    score: 88,
    rank: 2,
    profileViews: 38,
    documentViews: 19,
    interestsCount: 1,
    meetingsCount: 1,
    lastCalculated: new Date(),
    trend: 'up',
    change: 12,
  },
  {
    id: 'momentum-3',
    startupId: 'startup-3',
    score: 85,
    rank: 3,
    profileViews: 32,
    documentViews: 15,
    interestsCount: 1,
    meetingsCount: 1,
    lastCalculated: new Date(),
    trend: 'stable',
    change: 0,
  },
  {
    id: 'momentum-4',
    startupId: 'startup-4',
    score: 79,
    rank: 4,
    profileViews: 28,
    documentViews: 12,
    interestsCount: 1,
    meetingsCount: 1,
    lastCalculated: new Date(),
    trend: 'up',
    change: 8,
  },
  {
    id: 'momentum-5',
    startupId: 'startup-5',
    score: 71,
    rank: 5,
    profileViews: 22,
    documentViews: 8,
    interestsCount: 1,
    meetingsCount: 0,
    lastCalculated: new Date(),
    trend: 'down',
    change: -5,
  },
];

// Mock Startup Updates
export const mockStartupUpdates: StartupUpdate[] = [
  {
    id: 'update-1',
    startupId: 'startup-1',
    title: 'Closed First Enterprise Customer - Fortune 500 Bank',
    content: 'Excited to announce we\'ve signed our first enterprise customer! A Fortune 500 bank will be deploying NeuralFlow across their entire data infrastructure. This validates our GTM strategy and proves enterprise appetite for autonomous data agents.',
    metrics: {
      arr: 250000,
      customers: 1,
      growth: 100,
    },
    createdAt: new Date('2026-05-18'),
  },
  {
    id: 'update-2',
    startupId: 'startup-2',
    title: 'Phase 2 Clinical Trials Complete - 94% Accuracy Achieved',
    content: 'Our Phase 2 clinical trials are complete with incredible results. 94% accuracy in early cancer detection across 12 cancer types. FDA breakthrough designation application submitted. This is a massive milestone.',
    metrics: {
      trialsCompleted: 2,
      accuracy: 94,
      patientsTested: 1200,
    },
    createdAt: new Date('2026-05-17'),
  },
];